name: CI Release Tags

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release Tag
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          prerelease: false
          generateReleaseNotes: true