name: CI Release Tags

on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Setup & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Gradle unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  release:
    name: Release Tag
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Generate changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Release tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          prerelease: false
          generateReleaseNotes: true
          body: |
            ${{ steps.Changelog.outputs.changelog }}