name: CI Release Tags

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release Tag
    runs-on: ubuntu-latest

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.jar